services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - wp_site:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    secrets:
      - wpadmin
      - dbpass
    volumes:
      - wp_site:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    secrets:
      - wpadmin
      - dbpass
      - dbrootpass
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

secrets:
  wpadmin:
    file: ../secrets/credentials.txt
  dbpass:
    file: ../secrets/db_password.txt
  dbrootpass:
    file: ../secrets/db_root_password.txt

volumes:
  wp_site:
  wp_db:

networks:
  inception:
    driver: bridge
