services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - /home/ecarvalh/data/wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    restart: always
    secrets:
      - wpadmin
      - dbpass
    volumes:
      - /home/ecarvalh/data/wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    restart: always
    secrets:
      - wpadmin
      - dbpass
      - dbrootpass
    volumes:
      - /home/ecarvalh/data/mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

secrets:
  wpadmin:
    file: ../secrets/credentials.txt
  dbpass:
    file: ../secrets/db_password.txt
  dbrootpass:
    file: ../secrets/db_root_password.txt

networks:
  inception:
    driver: bridge
