services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    secrets:
      - wp_admin_pass
      - db_pass
    volumes:
      - wp_site:/var/www/html
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    secrets:
      - db_root_pass
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

secrets:
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  db_pass:
    file: ../secrets/db_pass.txt
  db_root_pass:
    file: ../secrets/db_root_pass.txt

volumes:
  wp_site:
  wp_db:

networks:
  inception:
    driver: bridge
