services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception_net
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    networks:
      - inception_net
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    networks:
      - inception_net
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    restart: always

networks:
  inception_net:
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/wp
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/db
